geany include/sensor_control.h &
geany src/sensor_control.cpp &
geany src/sensor_control_slots.cpp &
geany plugin_description.xml &
geany package.xml &
geany CMakeLists.txt &
geany msg/HokuyoCommand.msg &
geany msg/FleaCommand.msg &
geany msg/IMU.msg &
